# Generated by Django 5.2.5 on 2025-08-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactsubmission_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
