# Generated by Django 5.2.5 on 2025-09-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_menucategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='home.menucategory'),
        ),
    ]
