# Generated by Django 5.2.5 on 2025-10-02 02:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cart_cartitem_cart_cart_must_have_user_or_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Unique table number', unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of seats', validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('patio', 'Patio'), ('bar', 'Bar Area'), ('private', 'Private Dining')], default='indoor', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the table is in service')),
                ('description', models.TextField(blank=True, help_text='Optional description or special features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='home.restaurant')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['number'],
                'indexes': [models.Index(fields=['number'], name='home_table_number_cf91d7_idx'), models.Index(fields=['status'], name='home_table_status_05eb1e_idx'), models.Index(fields=['capacity'], name='home_table_capacit_decf7c_idx'), models.Index(fields=['location'], name='home_table_locatio_71fb42_idx')],
            },
        ),
    ]
