# Generated by Django 5.2.5 on 2025-10-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(help_text='Table number (unique per restaurant)'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'number')},
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'number'], name='home_table_restaur_6131eb_idx'),
        ),
    ]
