# Generated by Django 5.2.5 on 2025-10-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_table_number_alter_table_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_daily_special',
            field=models.BooleanField(default=False, help_text='Mark this item as a daily special to feature it prominently'),
        ),
    ]
