# Generated by Django 5.2.5 on 2025-10-15 05:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_menuitem_is_daily_special'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(help_text='Review comment or feedback')),
                ('review_date', models.DateTimeField(auto_now_add=True, help_text='When the review was created')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['menu_item'], name='home_userre_menu_it_645a7a_idx'), models.Index(fields=['user'], name='home_userre_user_id_51b06a_idx'), models.Index(fields=['rating'], name='home_userre_rating_ef9f2e_idx'), models.Index(fields=['-review_date'], name='home_userre_review__dcc1d5_idx')],
                'unique_together': {('user', 'menu_item')},
            },
        ),
    ]
