# Generated by Django 5.2.5 on 2025-10-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_userreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the category'),
        ),
    ]
