# Generated by Django 5.2.5 on 2025-10-18 03:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_menucategory_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Full name of the customer', max_length=100)),
                ('customer_email', models.EmailField(help_text='Email address for confirmation', max_length=254)),
                ('customer_phone', models.CharField(help_text='Phone number for contact', max_length=20)),
                ('party_size', models.PositiveIntegerField(help_text='Number of people in the party', validators=[django.core.validators.MinValueValidator(1)])),
                ('reservation_date', models.DateField(help_text='Date of the reservation')),
                ('reservation_time', models.TimeField(help_text='Time of the reservation')),
                ('duration_minutes', models.PositiveIntegerField(default=120, help_text='Expected duration in minutes (default: 2 hours)', validators=[django.core.validators.MinValueValidator(30)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=15)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.table')),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account (if registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['reservation_date', 'reservation_time'],
                'indexes': [models.Index(fields=['reservation_date', 'reservation_time'], name='home_reserv_reserva_4195f3_idx'), models.Index(fields=['table'], name='home_reserv_table_i_ac2e62_idx'), models.Index(fields=['status'], name='home_reserv_status_9e6d62_idx'), models.Index(fields=['customer_email'], name='home_reserv_custome_941908_idx'), models.Index(fields=['user'], name='home_reserv_user_id_dc03f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('table', 'reservation_date', 'reservation_time'), name='unique_table_datetime')],
            },
        ),
    ]
