# Generated by Django 5.2.5 on 2025-10-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_menuitem_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this item as featured to highlight it on the menu'),
        ),
    ]
