# Generated by Django 5.2.5 on 2025-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_menuitem_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or details about the ingredient')),
                ('is_allergen', models.BooleanField(default=False, help_text='Mark if this ingredient is a common allergen (nuts, dairy, gluten, etc.)')),
                ('is_vegetarian', models.BooleanField(default=True, help_text='Whether this ingredient is vegetarian')),
                ('is_vegan', models.BooleanField(default=False, help_text='Whether this ingredient is vegan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Ingredients used in this menu item', related_name='menu_items', to='home.ingredient'),
        ),
    ]
