# Generated by Django 5.2.5 on 2025-10-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_ingredient_menuitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='has_delivery',
            field=models.BooleanField(default=False, help_text='Indicates whether the restaurant offers delivery services'),
        ),
    ]
