# Generated by Django 5.2.5 on 2025-10-31 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_restaurant_has_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(help_text='Total calories per serving')),
                ('protein_grams', models.DecimalField(decimal_places=2, help_text='Protein content in grams', max_digits=5)),
                ('fat_grams', models.DecimalField(decimal_places=2, help_text='Fat content in grams', max_digits=5)),
                ('carbohydrate_grams', models.DecimalField(decimal_places=2, help_text='Carbohydrate content in grams', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(help_text='The menu item this nutritional information belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_info', to='home.menuitem')),
            ],
            options={
                'verbose_name': 'Nutritional Information',
                'verbose_name_plural': 'Nutritional Information',
            },
        ),
    ]
