# Generated by Django 5.2.5 on 2025-10-31 03:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_nutritionalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='calories',
            field=models.IntegerField(help_text='Total calories per serving', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='carbohydrate_grams',
            field=models.DecimalField(decimal_places=2, help_text='Carbohydrate content in grams', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='fat_grams',
            field=models.DecimalField(decimal_places=2, help_text='Fat content in grams', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='protein_grams',
            field=models.DecimalField(decimal_places=2, help_text='Protein content in grams', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
