# Generated by Django 5.2.5 on 2025-10-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_nutritionalinformation_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)', unique=True)),
                ('open_time', models.TimeField(help_text='Opening time for this day')),
                ('close_time', models.TimeField(help_text='Closing time for this day')),
                ('is_closed', models.BooleanField(default=False, help_text='Set to True if the restaurant is closed on this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Operating Hours',
                'verbose_name_plural': 'Daily Operating Hours',
                'ordering': ['day_of_week'],
            },
        ),
    ]
