# Generated by Django 5.2.5 on 2025-11-01 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_dailyoperatinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_date', models.DateField(help_text='Date when this item is featured as a daily special')),
                ('description', models.TextField(blank=True, help_text='Optional promotional description for this daily special')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(help_text='Menu item featured as a daily special', on_delete=django.db.models.deletion.CASCADE, related_name='daily_specials', to='home.menuitem')),
            ],
            options={
                'verbose_name': 'Daily Special',
                'verbose_name_plural': 'Daily Specials',
                'ordering': ['special_date'],
                'unique_together': {('menu_item', 'special_date')},
            },
        ),
    ]
