# Generated by Django 5.2.5 on 2025-11-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_dailyspecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyspecial',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional promotional description for this daily special'),
        ),
    ]
