# Generated by Django 5.2.5 on 2025-09-27 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_driver_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_year',
            field=models.PositiveIntegerField(help_text='Vehicle manufacturing year', validators=[django.core.validators.MinValueValidator(1980, message='Vehicle year must be 1980 or later')]),
        ),
    ]
