# Generated by Django 5.2.5 on 2025-09-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_driver_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique alphanumeric order identifier (e.g., ORD-A7X9K2M5)', max_length=20, null=True),
        ),
    ]
