# Generated by Django 5.2.5 on 2025-09-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_populate_order_ids_step2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique alphanumeric order identifier (e.g., ORD-A7X9K2M5)', max_length=20, null=True, unique=True),
        ),
    ]
