# Generated by Django 5.2.5 on 2025-10-02 00:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_unique_constraint_step3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SAVE10, WELCOME20)', max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10% off)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Discount must be at least 0.01%'), django.core.validators.MaxValueValidator(Decimal('100.00'), message='Discount cannot exceed 100%')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is currently active and can be used')),
                ('valid_from', models.DateField(help_text='Date from when the coupon becomes valid')),
                ('valid_until', models.DateField(help_text='Date until when the coupon remains valid (inclusive)')),
                ('description', models.TextField(blank=True, help_text='Optional description of the coupon offer')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('max_usage', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null for unlimited)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
