# Generated by Django 5.2.5 on 2025-10-03 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(help_text='Human-readable pickup address', max_length=500)),
                ('pickup_lat', models.DecimalField(decimal_places=6, help_text='Pickup latitude coordinate', max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, help_text='Pickup longitude coordinate', max_digits=9)),
                ('dropoff_address', models.CharField(help_text='Human-readable dropoff address', max_length=500)),
                ('drop_lat', models.DecimalField(decimal_places=6, help_text='Dropoff latitude coordinate', max_digits=9)),
                ('drop_lng', models.DecimalField(decimal_places=6, help_text='Dropoff longitude coordinate', max_digits=9)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', help_text='Current status of the ride', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the ride was requested')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the ride was updated')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the driver accepted the ride', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the ride was completed', null=True)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated fare for the ride', max_digits=10, null=True)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, help_text='Final calculated fare after completion', max_digits=10, null=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this ride (null until accepted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='orders.driver')),
                ('rider', models.ForeignKey(help_text='Rider who requested this ride', on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='orders.rider')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='orders_ride_status_3fc137_idx'), models.Index(fields=['rider', 'status'], name='orders_ride_rider_i_11fed0_idx'), models.Index(fields=['driver', 'status'], name='orders_ride_driver__0dfcc6_idx')],
            },
        ),
    ]
