# Generated by Django 5.2.5 on 2025-10-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated fare using distance and surge multiplier', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was marked as complete', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card')], help_text='Method used for payment (Cash, UPI, Card)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', help_text='Payment status of the ride', max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='surge_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Surge multiplier for peak hours (1.0 = normal, 1.5 = 50% surge)', max_digits=3),
        ),
    ]
