# Generated by Django 5.2.5 on 2025-10-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_ride_fare_ride_paid_at_ride_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='availability_status',
            field=models.CharField(choices=[('offline', 'Offline'), ('available', 'Available')], default='offline', help_text='Current availability for accepting rides', max_length=15),
        ),
    ]
