# Generated by Django 5.2.5 on 2025-11-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_update_driver_availability_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the loyalty tier (e.g., 'Silver Member')", max_length=50, unique=True)),
                ('points_required', models.IntegerField(help_text='Minimum number of loyalty points required to reach this tier', unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount for customers in this tier (e.g., 5.00 for 5%)', max_digits=5)),
                ('description', models.TextField(help_text='Brief explanation of the benefits for this tier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
                'ordering': ['points_required'],
            },
        ),
    ]
