# Generated by Django 5.2.5 on 2025-11-01 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_loyaltyprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Percentage discount for customers in this tier (0-100%, e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points_required',
            field=models.IntegerField(help_text='Minimum number of loyalty points required to reach this tier (must be 0 or greater)', unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
