# Generated by Django 5.2.5 on 2025-11-02 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_loyaltyprogram_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag to indicate if the program is currently active'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_per_dollar_spent',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='How many loyalty points a customer earns for each dollar spent (e.g., 1.0 for 1 point per dollar)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
