# Generated by Django 5.2.5 on 2025-11-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_loyaltyprogram_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the payment method (e.g., 'Credit Card', 'Cash', 'Online Wallet')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief explanation of the payment method', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this payment method is currently available for use')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
            },
        ),
    ]
